# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_auto_20170925_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
