# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fms', '0003_auto_20170925_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('is_verified', models.BooleanField()),
                ('token', models.IntegerField()),
            ],
        ),
    ]
