# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0004_user_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='user_info',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
