# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0005_auto_20170925_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='register_date',
            field=models.DateTimeField(null=True),
        ),
    ]
