# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0006_user_info_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
