# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0007_user_info_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate_info',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_resolved', models.BooleanField()),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
