# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0008_donate_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_info',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
                ('item_amount', models.IntegerField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='donate_info',
            name='request_date',
            field=models.DateField(null=True),
        ),
    ]
