# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0009_auto_20171002_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_info',
            name='food_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='donate_info',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donate_info',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
