# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import fms.models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0010_auto_20171002_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_info',
            name='food_image',
            field=models.FileField(null=True, upload_to=fms.models.get_upload_file_name),
        ),
    ]
