# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0011_auto_20171002_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_info',
            name='item_amount',
            field=models.CharField(max_length=100),
        ),
    ]
