# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0013_auto_20171002_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_info',
            name='request_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
