# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0014_auto_20171002_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_info',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
