# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0017_new_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_applicants',
            name='id',
        ),
        migrations.AlterField(
            model_name='new_applicants',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
